In [1]:
import numpy as np
import pandas as pd

### 什么是DataFrame？

DataFrame就是表格型数据结构

### 创建DataFrame

In [3]:
# 方法一：通过字典创建
# key  : DataFrame列索引名称
# value: DataFrame列
m = pd.DataFrame({
    "a": [1, 2, 3, 4],
    "b": [5, 6, 7, 8],
    "c": [9, 0, 1, 2]
})
print("<m>\n", m)

# 查看行索引
print("<index>\n", m.index)

# 查看列索引
print("<columns>\n", m.columns)

# 查看数据
print("<values>\n", m.values)

<m>
    a  b  c
0  1  5  9
1  2  6  0
2  3  7  1
3  4  8  2
<index>
 RangeIndex(start=0, stop=4, step=1)
<columns>
 Index(['a', 'b', 'c'], dtype='object')
<values>
 [[1 5 9]
 [2 6 0]
 [3 7 1]
 [4 8 2]]


In [11]:
# 方法二：通过ndarray创建（自定义指定行列索引）
pd.DataFrame(
    np.arange(12).reshape((3, 4)), 
    index = ['x', 'y', 'z'], 
    columns = ['w1', 'w2', 'w3', 'w4'])

w1  w2  w3  w4
x   0   1   2   3
y   4   5   6   7
z   8   9  10  11

In [19]:
# 方法三：通过Series构成的字典创建
pd.DataFrame({
    "X": pd.Series(np.arange(3)),
    "Y": pd.Series(np.arange(3, 6))
})

X  Y
0  0  3
1  1  4
2  2  5

In [21]:
# 方法四：通过字典构成的字典创建
pd.DataFrame({
    "w1": {"X": 1, "Y": 1, "Z": 2},
    "w2": {"X": 2, "Y": 3, "Z": 2}
})

w1  w2
X   1   2
Y   1   3
Z   2   2

In [22]:
# 方法五：通过字典构成的列表创建
# ⚠️ 列表中每个字典对应DataFrame中的一行（Row）
pd.DataFrame([
    {"X": 1, "Y": 1, "Z": 2},
    {"X": 2, "Y": 3, "Z": 2}
])

X  Y  Z
0  1  1  2
1  2  3  2

In [25]:
# 方法六：通过Series构成的列表创建
# ⚠️ 列表中每个Series对应DataFrame中的一行（Row）
idx = ['X', 'Y', 'Z']
pd.DataFrame([
    pd.Series([1, 1, 2], index = idx),
    pd.Series([2, 3, 2], index = idx)
])

X  Y  Z
0  1  1  2
1  2  3  2

### 基本操作

In [39]:
matrix = pd.DataFrame(
    np.arange(12).reshape((3, 4)), 
    index = ['x', 'y', 'z'], 
    columns = ['W1', 'W2', 'W3', 'W4'])
matrix

W1  W2  W3  W4
x   0   1   2   3
y   4   5   6   7
z   8   9  10  11

#### 转置

In [29]:
matrix.T

x  y   z
W1  0  4   8
W2  1  5   9
W3  2  6  10
W4  3  7  11

#### 获取列数据

⚠️ 每一列对应一个Series

In [30]:
matrix['W2']

x    1
y    5
z    9
Name: W2, dtype: int64

In [33]:
# 获取多列
matrix[['W3', 'W4']]

W3  W4
x   2   3
y   6   7
z  10  11

#### 添加列

In [41]:
matrix['W5'] = [2, 4, 5]
# matrix['W5'] = 1 等价于 matrix['W5'] = [1, 1, 1]
matrix

W1  W2  W3  W4  W5
x   0   1   2   3   2
y   4   5   6   7   4
z   8   9  10  11   5

#### 修改列

In [42]:
matrix['W5'] = 1
matrix

W1  W2  W3  W4  W5
x   0   1   2   3   1
y   4   5   6   7   1
z   8   9  10  11   1

#### 删除列

In [43]:
del(matrix['W5'])
matrix

W1  W2  W3  W4
x   0   1   2   3
y   4   5   6   7
z   8   9  10  11