In [1]:
import numpy as np

### 数组与数计算

In [4]:
nd = np.random.randint(0, 10, (3, 3))
print("<nd>\n", nd)
print("<nd ✖️ 2>\n", nd * 2)

<nd>
 [[9 5 5]
 [1 6 3]
 [9 5 0]]
<nd ✖️ 2>
 [[18 10 10]
 [ 2 12  6]
 [18 10  0]]


### 数组与数组计算

In [5]:
# 同形状运算
nd1 = np.random.randint(0, 10, (3, 3)) 
nd2 = np.random.randint(0, 10, (3, 3)) 
print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd1 + nd2>\n", nd1 + nd2)

<nd1>
 [[1 1 8]
 [2 9 8]
 [9 8 4]]
<nd2>
 [[7 9 5]
 [0 1 9]
 [1 1 6]]
<nd1 + nd2>
 [[ 8 10 13]
 [ 2 10 17]
 [10  9 10]]


In [8]:
# ❌ 异形状运算
nd1 = np.random.randint(0, 10, (2, 3)) 
nd2 = np.random.randint(0, 10, (2, 2)) 
print("<nd1 + nd2>\n", nd1 + nd2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [9]:
# ✅ 异形状运算
# 行数相同，列数不同，有数组的列为1
nd1 = np.random.randint(0, 10, (3, 3)) 
nd2 = np.random.randint(0, 10, (3, 1)) # 进行广播📢
print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd1 + nd2>\n", nd1 + nd2)

<nd1>
 [[1 1 0]
 [0 0 9]
 [7 1 7]]
<nd2>
 [[9]
 [6]
 [3]]
<nd1 + nd2>
 [[10 10  9]
 [ 6  6 15]
 [10  4 10]]


In [11]:
# ✅ 异形状运算
# 行数不同，列数相同，有数组的行为1
nd1 = np.random.randint(0, 10, (1, 3)) # 进行广播📢
nd2 = np.random.randint(0, 10, (3, 3)) 
print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd1 + nd2>\n", nd1 + nd2)

<nd1>
 [[9 5 7]]
<nd2>
 [[3 0 6]
 [2 1 4]
 [9 5 2]]
<nd1 + nd2>
 [[12  5 13]
 [11  6 11]
 [18 10  9]]


### 广播原则

如果两个数组的后缘维度（即从后数组形状元组的最后一个元素开始向前考察）的轴长度相符或者其中一方的长度为1，则认为数组之间是广播兼容的。广播会在缺失长度为1维度上进行扩充。

Q1: A(3, 8, 2) + B(8, 3) = ?

A:  ❌

    A的第3维度[2] != B的第2维度[3]

Q1: A(3, 8, 2) + B(8, 1) = ?
    
A:  ✅
    
    A的第3维度[2] != B的第2维度[1]
    
    B的第2维度为1，则B广播

Q1: A(3, 1, 8) + B(8, 1) = ?
    
A:  ✅
    
    A的第3维度[8] != B的第2维度[1]
    
    B的第2维度为1，则B广播
    

In [25]:
# 转置和数组相乘
A = np.random.randint(0, 5, (2, 3))
B = A.T
C = A.dot(B)

print("A\n", A)
print("B\n", B)
print("C=AB\n", C)

A
 [[4 1 0]
 [4 3 3]]
B
 [[4 4]
 [1 3]
 [0 3]]
C=AB
 [[17 19]
 [19 34]]
