In [1]:
import numpy as np

### 不拷贝

直接赋值的方式指向堆区同一块数据

In [4]:
a = np.arange(12)
b = a
print("<b == a>", b is a)

# 尝试修改查看原来的对象是否改变，来证明是不是深拷贝
a[0] = 100
print("a = ", a)
print("b = ", b)

<b == a> True
a =  [100   1   2   3   4   5   6   7   8   9  10  11]
b =  [100   1   2   3   4   5   6   7   8   9  10  11]


### view方法进行浅拷贝

这种方式只会进行变量拷贝，即只会拷贝栈区数据，不会拷贝堆区数据

In [6]:
a = np.arange(12)
b = a.view()
print("<b == a>", b is a)

# 尝试修改之后 查看原来的对象发生了改变，证明view方法不是深拷贝
a[0] = 100
print("a = ", a)
print("b = ", b)

<b == a> False
a =  [100   1   2   3   4   5   6   7   8   9  10  11]
b =  [100   1   2   3   4   5   6   7   8   9  10  11]


### copy方法进行深拷贝

这种方式会将栈区和堆区的数据一起拷贝

In [7]:
a = np.arange(12)
b = a.copy()
print("<b == a>", b is a)

# 尝试修改之后 查看原来的对象没有发生改变，证明copy方法是深拷贝
a[0] = 100
print("a = ", a)
print("b = ", b)

<b == a> False
a =  [100   1   2   3   4   5   6   7   8   9  10  11]
b =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


### ravel方法和flatten方法

ravel方法是浅拷贝

In [12]:
a = np.arange(12).reshape((3, 4))
b = a.ravel()

# 修改新的数组会改变原来的数组，证明指向的是堆区同一块数据，则为浅拷贝
b[0] = 100
print("<a>\n", a)
print("<b>\n", b)

<a>
 [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
<b>
 [100   1   2   3   4   5   6   7   8   9  10  11]


flatten方法是深拷贝

In [13]:
a = np.arange(12).reshape((3, 4))
b = a.flatten()

# 修改新的数组会改变原来的数组，证明指向的不是堆区同一块数据，则为深拷贝
b[0] = 100
print("<a>\n", a)
print("<b>\n", b)

<a>
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<b>
 [100   1   2   3   4   5   6   7   8   9  10  11]
