In [1]:
import numpy as np

### 操作CSV文件

In [4]:
score = np.random.randint(80, 100, size = (50, 2))
score[:5,:]

array([[87, 83],
       [86, 88],
       [80, 89],
       [88, 98],
       [93, 84]])

#### 1.保存文件

In [7]:
# fmt设置为%d，为了防止保存整数保存文件之后禁用科学记数法
# comments设置为“”，为了防止保存的表头没有#号
np.savetxt("score.csv", score, delimiter = ",", header = "Math,English", comments = "", fmt = "%d")

#### 2.读取文件

In [12]:
# dtype指定读取的数据类型
# delimiter指定读取数据的分割符
# skiprows指定读取数据时跳过几行进行读取，因为这里读取文件的第一行是表头
_score = np.loadtxt("./data/score.csv", dtype = np.int64, delimiter = ",", skiprows = 1)
_score[:10,:]

array([[87, 83],
       [86, 88],
       [80, 89],
       [88, 98],
       [93, 84],
       [89, 98],
       [85, 89],
       [94, 92],
       [82, 81],
       [87, 90]])

### numpy原生的文件存储

numpy原生的文件存储可以读写高维数组，而通过csv的文件存储只能读写二维数组

#### 1.保存

save方法保存的是.npy文件

savez方法保存的是.npz文件，该文件是经过压缩的

In [16]:
score = np.random.randint(0, 10, size = (2, 2, 2))
np.save("./data/score", score)

#### 2.读取

In [17]:
np.load("./data/score.npy")

array([[[7, 1],
        [4, 6]],

       [[7, 6],
        [3, 0]]])