In [1]:
import numpy as np

### 一维数组索引与切片

In [8]:
arr = np.arange(10)
print("<arr> ", arr)

# 查询下标4的元素
print("arr[4] = ", arr[4])

# 查询下标范围在[4, 6)的元素
print("arr[4:6] = ", arr[4:6])

# 查询下标范围在[1, 10) 并且[1, 10)中步长为2的元素（即：下标为1,3,5,7,9的元素）
print("arr[1:10:2] = ", arr[1:10:2])

# 查询倒数第一个元素
print("arr[-1] = ", arr[-1])

# 查询倒数第二个元素
print("arr[-2] = ", arr[-2])

<arr>  [0 1 2 3 4 5 6 7 8 9]
arr[4] =  4
arr[4:6] =  [4 5]
arr[1:10:2] =  [1 3 5 7 9]
arr[-1] =  9
arr[-2] =  8


### 二维数组索引与切片

In [12]:
matrix = np.random.randint(0, 10, size = (4, 6))
print("<matrix>\n ", matrix)

<matrix>
  [[4 5 5 1 8 9]
 [2 5 0 1 4 9]
 [1 3 3 2 9 6]
 [1 5 0 9 5 2]]


In [15]:
## 按行索引和切片
## ⚠️ 如果二维数组中的索引与切片只有一个值，则就是按行进行索引与切片

# 查询第0行
print("<matrix[0]>\n ", matrix[0])

# 查询多行，并且行索引范围是[1, 3)
print("<matrix[1:3]>\n ", matrix[1:3])

# 查询第0行，第2行和第3行
print("<matrix[[0, 2, 3]]>\n ", matrix[[0, 2, 3]])

<matrix[0]>
  [4 5 5 1 8 9]
<matrix[1:3]>
  [[2 5 0 1 4 9]
 [1 3 3 2 9 6]]
<matrix[[0, 2, 3]]>
  [[4 5 5 1 8 9]
 [1 3 3 2 9 6]
 [1 5 0 9 5 2]]


In [19]:
## 按列索引和切片

# 查询第0列
print("<matrix[:,0]>\n ", matrix[:,0])

# 查询多列，并且列索引范围是[1, 3)
print("<matrix[:,1:3]>\n ", matrix[:,1:3])

# 查询第0列，第2列和第3列
print("<matrix[:,[0, 2, 3]]>\n ", matrix[:,[0, 2, 3]])

<matrix[:,0]>
  [4 2 1 1]
<matrix[:,1:3]>
  [[5 5]
 [5 0]
 [3 3]
 [5 0]]
<matrix[:,[0, 2, 3]]>
  [[4 5 1]
 [2 0 1]
 [1 3 2]
 [1 0 9]]


In [23]:
## 按行和列进行索引和切片

# 查询第2行，第1列的元素
print("<matrix[2, 1]>\n ", matrix[2, 1])

# 获取第1行，第4列的元素以及第2行，第5列的元素
print("<matrix[[1, 2], [4, 5]]>\n ", matrix[[1, 2], [4, 5]])

# 获取行下表范围是[1, 3) 列下表范围是[4, 6)所包含的和元素
print("<matrix[1:3, 4:6]>\n ", matrix[1:3, 4:6])

<matrix[2, 1]>
  3
<matrix[[1, 2], [4, 5]]>
  [4 6]
<matrix[1:3, 4:6]>
  [[4 9]
 [9 6]]


### 布尔索引

In [27]:
m = np.arange(24).reshape((4, 6))
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
print("<m < 10>\n", m < 10)

# 提取矩阵中元素小于10的值
print("<m[m < 10]>\n", m[m < 10])

# 提取矩阵中元素小于5或者大于10的值
print("<m[(m < 5) | (m > 10)]>\n", m[(m < 5) | (m > 10)])

<m < 10>
 [[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
<m[m < 10]>
 [0 1 2 3 4 5 6 7 8 9]
<m[(m < 5) | (m > 10)]>
 [ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]
