In [1]:
import numpy as np

### 数组维度

In [2]:
vector = np.array([1, 2, 3, 4])

matrix = np.array([[1, 2, 3, 4], [4, 3, 1, 2]])

tensor = np.array([
    [[1, 2, 3, 4], [4, 3, 1, 2]],
    [[0, 1, 2, 1], [8, 2, 1, 3]]
])

print("<vector dim>, ", vector.ndim)
print("<matrix dim>, ", matrix.ndim)
print("<tensor dim>, ", tensor.ndim)

<vector dim>,  1
<matrix dim>,  2
<tensor dim>,  3


### 数组形状

In [3]:
print("<vector shape>, ", vector.shape)
print("<matrix shape>, ", matrix.shape)
print("<tensor shape>, ", tensor.shape)

<vector shape>,  (4,)
<matrix shape>,  (2, 4)
<tensor shape>,  (2, 2, 4)


### 形状重构

In [5]:
# 三维数组变形为二维数组
tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

tensor_to_matrix = tensor.reshape((2, 6))
tensor_to_matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# 三维数组变形为一维数组或者单列/单行矩阵

# 方法一：reshape重构
# 单行矩阵
print("<1, 12>\n", tensor.reshape((1, 12)))
# 单列矩阵
print("<12, 1>\n", tensor.reshape((12, 1)))
# 一位数组
print("<12,  >\n", tensor.reshape((12,  )))

# 方法二：扁平化
# flatten函数等价于reshape((N,  ))
print("<12,  >\n", tensor.flatten())

<1, 12>
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
<12, 1>
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
<12,  >
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
<12,  >
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


### 元素个数和占用大小

In [29]:
vector = np.arange(12)
print("<vector> ", vector)
print("<dtype> ", vector.dtype)
# 数组元素个数
print("<size> ", vector.size)
# 数组元素大小（占用字节）
print("<itemsize> ", vector.itemsize)
# 数组总占用
print("<total size> ", vector.itemsize * vector.size)

<vector>  [ 0  1  2  3  4  5  6  7  8  9 10 11]
<dtype>  int64
<size>  12
<itemsize>  8
<total size>  96
