In [7]:
import numpy as np

### Python中的列表

In [8]:
# Python中的列表，可以存放数据类型不同的元素
a = [1, 2, 3, '4']
a

[1, 2, 3, '4']

### Numpy中的数组

In [14]:
# 通过Python列表构建Numpy数组
# ⚠️ 如果列表中有一个元素为字符串，则转换的Numpy数组中所有的元素均为字符串
# ⚠️ 虽然列表中可以有不同元素，但仍然建议所有元素类型统一，避免框架自动类型转换
b = np.array(a)
b

array(['1', '2', '3', '4'], dtype='<U21')

### 创建数组的方式

In [29]:
# 方式一：通过列表创建数组
arr1 = np.array([1, 0, 1, 0])
print("<arr1>", arr1)
# numpy数组类型<numpy.ndarray>
print("<arr1 type>", type(arr1))

<arr1> [1 0 1 0]
<arr1 type> <class 'numpy.ndarray'>


In [30]:
# 方式二：通过序列快速创建数组（使用arange函数）
# 创建一个[0, 10)区间默认步长为1的整数数组
arr2 = np.arange(10)
print("<arr2>", arr2)
# 创建一个[20, 30)区间步长为2的整数数组
arr3 = np.arange(20, 30, 2)
print("<arr3>", arr3)

<arr2> [0 1 2 3 4 5 6 7 8 9]
<arr3> [20 22 24 26 28]


In [36]:
# 方式三：通过随机方式创建数组（使用np.random模块）
# 创建一个2✖️2的随机数组（默认类型为浮点型），元素取值范围默认为：[0, 1)
arr4 = np.random.random((2, 2))
print("<arr4>\n", arr4)
# 创建一个3✖️3的随机整数数组，元素取值范围：[0, 10)
arr5 = np.random.randint(0, 10, size = (3, 3))
print("<arr5>\n", arr5)

<arr4>
 [[0.1149907  0.77687515]
 [0.28884707 0.11803274]]
<arr5>
 [[2 0 2]
 [1 2 2]
 [3 0 8]]


In [42]:
# 方式四：使用函数生成特殊数组
# 生成一个2✖️3的全0数组
a1 = np.zeros((2, 3))
print("<a1>\n", a1)
# 生成一个3✖️2的全1数组
a2 = np.ones((3, 2))
print("<a2>\n", a2)
# 生成一个2✖️2的全6数组
a3 = np.full((2, 2), 6)
print("<a3>\n", a3)
# 生成一个3✖️3的对角矩阵，且对角线元素为1
m = np.eye(3)
print("<m>\n", m)

<a1>
 [[0. 0. 0.]
 [0. 0. 0.]]
<a2>
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
<a3>
 [[6 6]
 [6 6]]
<m>
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 数组的数据类型

In [49]:
i = np.arange(5)
# numpy.ndarray中可以通过dtype属性查看数组中元素类型
print("<i dtype>", i.dtype)

d = np.array([1.0, 2.1, 3.1])
print("<d dtype>", d.dtype)

<i dtype> int64
<d dtype> float64


In [56]:
# 指定元素类型创建数组
# 整数类型
v1 = np.array([1, 2, 3, 4], dtype = 'i')
print("<v1 dtype>", v1.dtype)

# 浮点类型
v2 = np.array([1, 2, 3, 4], dtype = np.float16)
print("<v2 dtype>", v2.dtype)

# 复合类型
class Person:
    def __init__(self ,name, age):
        self.name = name
        self.age = age
        
v3 = np.array([Person("a", 1), Person("b", 2)])
print("<v3 dtype>", v3.dtype)

# 字符串（二进制）
v4 = np.array(['1', '2', '3', '4'], dtype = 'S')
print("<v4>", v4)
# |S1 表示字符串的二进制表现形式
print("<v4 dtype>", v4.dtype)

# 字符串（Unicode）
v5 = np.array(['1', '2', '3', '4'])
print("<v5>", v5)
# <U1
print("<v5 dtype>", v5.dtype)

<v1 dtype> int32
<v2 dtype> float16
<v3 dtype> object
<v4> [b'1' b'2' b'3' b'4']
<v4 dtype> |S1
<v5> ['1' '2' '3' '4']
<v5 dtype> <U1


In [57]:
# 数据类型强转
a = np.array([1, 2, 3, 4])
b = a.astype("U")
print("<a>", a)
print("<a dtype>", a.dtype)
print("<b>", b)
print("<b dtype>", b.dtype)

<a> [1 2 3 4]
<a dtype> int64
<b> ['1' '2' '3' '4']
<b dtype> <U21
