In [1]:
import numpy as np

### 叠加

1.vstack：将数组在**垂直**方向上进行叠加，前提是数组的列必须要相同。

In [6]:
nd1 = np.random.randint(0, 5, size = (3, 5))
nd2 = np.random.randint(0, 5, size = (1, 5))
nd3 = np.vstack([nd1, nd2])

print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd3>\n", nd3)

<nd1>
 [[1 0 1 1 1]
 [1 0 0 2 4]
 [1 0 3 1 2]]
<nd2>
 [[2 3 1 4 0]]
<nd3>
 [[1 0 1 1 1]
 [1 0 0 2 4]
 [1 0 3 1 2]
 [2 3 1 4 0]]


2.hstack：将数组在**水平**方向上进行叠加，前提是数组的行必须要相同。

In [8]:
nd1 = np.random.randint(0, 5, size = (3, 5))
nd2 = np.random.randint(0, 5, size = (3, 1))
nd3 = np.hstack([nd1, nd2])

print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd3>\n", nd3)

<nd1>
 [[1 1 1 3 0]
 [4 0 2 0 0]
 [1 1 4 4 1]]
<nd2>
 [[0]
 [3]
 [4]]
<nd3>
 [[1 1 1 3 0 0]
 [4 0 2 0 0 3]
 [1 1 4 4 1 4]]


3.concatenate：将数组在水平或者垂直方向进行叠加，具体方向通过axis参数轴进行指定

axis=0    代表垂直方向叠加（默认）

axis=1    代表水平方向叠加

axis=None 代表叠加为一位数组

In [11]:
# 垂直叠加
nd1 = np.random.randint(0, 5, size = (3, 5))
nd2 = np.random.randint(0, 5, size = (1, 5))
nd3 = np.concatenate([nd1, nd2], axis=0)

print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd3>\n", nd3)

<nd1>
 [[4 2 1 4 1]
 [3 4 3 4 3]
 [1 4 4 1 3]]
<nd2>
 [[2 1 3 0 4]]
<nd3>
 [[4 2 1 4 1]
 [3 4 3 4 3]
 [1 4 4 1 3]
 [2 1 3 0 4]]


In [12]:
# 水平叠加
nd1 = np.random.randint(0, 5, size = (3, 5))
nd2 = np.random.randint(0, 5, size = (3, 1))

nd3 = np.concatenate([nd1, nd2], axis=1)

print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd3>\n", nd3)

<nd1>
 [[4 4 1 0 4]
 [1 0 2 1 1]
 [1 2 0 1 2]]
<nd2>
 [[3]
 [4]
 [2]]
<nd3>
 [[4 4 1 0 4 3]
 [1 0 2 1 1 4]
 [1 2 0 1 2 2]]


In [13]:
# 叠加为一维数组
nd1 = np.random.randint(0, 5, size = (2, 3))
nd2 = np.random.randint(0, 5, size = (3, 2))

nd3 = np.concatenate([nd1, nd2], axis=None)

print("<nd1>\n", nd1)
print("<nd2>\n", nd2)
print("<nd3>\n", nd3)

<nd1>
 [[1 3 3]
 [2 3 0]]
<nd2>
 [[3 4]
 [3 2]
 [1 2]]
<nd3>
 [1 3 3 2 3 0 3 4 3 2 1 2]


### 切割

1.hsplit： 水平切割。指定分割为几列，可以使用数字代表分成几个部分，也可以使用数组来代表切割的位置

In [20]:
# 平均切割
nd = np.random.randint(0, 5, size = (3, 4))
# 平均分割为2份
# ⚠️ 如果数组的列数不能被切割数量整除，则会产生异常：array split does not result in an equal division
(part1, part2) = np.hsplit(nd, 2)

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)

<nd>
 [[1 2 4 2]
 [4 1 1 4]
 [1 4 0 1]]
<part1>
 [[1 2]
 [4 1]
 [1 4]]
<part2>
 [[4 2]
 [1 4]
 [0 1]]


In [21]:
# 指定位置切割
nd = np.random.randint(0, 5, size = (3, 5))
# 在第2列和第3列进行切割
(part1, part2, part3) = np.hsplit(nd, (1, 2))

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)
print("<part3>\n", part3)

<nd>
 [[0 1 2 2 0]
 [4 0 3 0 1]
 [4 3 1 0 3]]
<part1>
 [[0]
 [4]
 [4]]
<part2>
 [[1]
 [0]
 [3]]
<part3>
 [[2 2 0]
 [3 0 1]
 [1 0 3]]


2.vsplit： 垂直切割。指定分割为几行，可以使用数字代表分成几个部分，也可以使用数组来代表切割的位置

In [23]:
# 平均切割
nd = np.random.randint(0, 5, size = (4, 3))
# 平均分割为2份
# ⚠️ 如果数组的行数不能被切割数量整除，则会产生异常：array split does not result in an equal division
(part1, part2) = np.vsplit(nd, 2)

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)

<nd>
 [[3 1 0]
 [2 3 3]
 [0 2 1]
 [3 4 3]]
<part1>
 [[3 1 0]
 [2 3 3]]
<part2>
 [[0 2 1]
 [3 4 3]]


In [26]:
# 指定位置切割
nd = np.random.randint(0, 5, size = (5, 3))
# 在第2行和第4行进行切割
(part1, part2, part3) = np.vsplit(nd, (1, 3))

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)
print("<part3>\n", part3)

<nd>
 [[1 2 3]
 [1 4 0]
 [1 0 2]
 [0 0 4]
 [4 1 3]]
<part1>
 [[1 2 3]]
<part2>
 [[1 4 0]
 [1 0 2]]
<part3>
 [[0 0 4]
 [4 1 3]]


3.split：通过不同的方式进行切割

axis=0 代表按行（默认）

axis=1 代表按列

In [27]:
# 按行切割
nd = np.random.randint(0, 5, size = (5, 3))
(part1, part2, part3) = np.split(nd, (1, 3), axis = 0)

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)
print("<part3>\n", part3)

<nd>
 [[4 0 1]
 [4 1 1]
 [4 3 4]
 [2 3 0]
 [2 2 3]]
<part1>
 [[4 0 1]]
<part2>
 [[4 1 1]
 [4 3 4]]
<part3>
 [[2 3 0]
 [2 2 3]]


In [28]:
# 按列切割
nd = np.random.randint(0, 5, size = (3, 5))
(part1, part2, part3) = np.split(nd, (1, 3), axis = 1)

print("<nd>\n", nd)
print("<part1>\n", part1)
print("<part2>\n", part2)
print("<part3>\n", part3)

<nd>
 [[3 4 2 2 1]
 [0 0 1 1 2]
 [3 2 1 4 3]]
<part1>
 [[3]
 [0]
 [3]]
<part2>
 [[4 2]
 [0 1]
 [2 1]]
<part3>
 [[2 1]
 [1 2]
 [4 3]]
