In [1]:
import numpy as np

In [3]:
matrix = np.random.randint(0, 10, size = (4, 6))
matrix

array([[7, 9, 8, 0, 4, 7],
       [0, 5, 9, 4, 2, 0],
       [4, 5, 8, 8, 3, 6],
       [0, 8, 0, 1, 4, 1]])

In [4]:
# 将矩阵第2行修改为0
# ⚠️ 此操作会修改原始数组
matrix[1] = 0
matrix

array([[7, 9, 8, 0, 4, 7],
       [0, 0, 0, 0, 0, 0],
       [4, 5, 8, 8, 3, 6],
       [0, 8, 0, 1, 4, 1]])

In [6]:
# 将矩阵第2行修改为指定的行
# ⚠️ 此操作会修改原始数组
matrix[1] = np.array([0, 5, 9, 4, 2, 0])
matrix

array([[7, 9, 8, 0, 4, 7],
       [0, 5, 9, 4, 2, 0],
       [4, 5, 8, 8, 3, 6],
       [0, 8, 0, 1, 4, 1]])

In [7]:
# 将矩阵中元素小于3的替换为1
# ⚠️ 此操作会修改原始数组
matrix[matrix < 3] = 1
matrix

array([[7, 9, 8, 1, 4, 7],
       [1, 5, 9, 4, 1, 1],
       [4, 5, 8, 8, 3, 6],
       [1, 8, 1, 1, 4, 1]])

In [9]:
# 将矩阵中元素大于4的替换为1，反之替换为0
# ⚠️ 此操作不会修改原始数组
new_matrix = np.where(matrix > 4, 1, 0)
print("<matrix>\n", matrix)
print("<new_matrix>\n", new_matrix)

<matrix>
 [[7 9 8 1 4 7]
 [1 5 9 4 1 1]
 [4 5 8 8 3 6]
 [1 8 1 1 4 1]]
<new_matrix>
 [[1 1 1 0 0 1]
 [0 1 1 0 0 0]
 [0 1 1 1 0 1]
 [0 1 0 0 0 0]]
