In [1]:
import numpy as np

### 随机数种子

通过seed函数指定随机数生成时所使用算法开始的数值，如果使用相同的seed值，则每次生成的随机数都相同；如果不设置这个值，则会根据系统时间来自己选择这个值，此时每次生成的随机数因为时间差异而不同。

In [6]:
np.random.seed(42)

# ⚠️
#    （1）这里的随机数相同是指每次执行的结果都相同
#    （2）随机数种子只对下一次随机数的产生有影响
print("rand =", np.random.rand())
print("rand =", np.random.rand())

rand = 0.3745401188473625
rand = 0.9507143064099162


#### rand

随机产生[0, 1)之间的随机数

In [8]:
print("rand value\n", np.random.rand())
print("rand matrix\n", np.random.rand(2, 3))

rand value
 0.5986584841970366
rand matrix
 [[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]]


#### randn

随机生成服从 μ = 0, σ = 1 的标准正态分布的值

In [10]:
np.random.randn(3, 4)

array([[-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

#### randint

随机生成制指定范围内的随机整数

In [11]:
# 生成[0, 10)之间的随机整数
np.random.randint(10, size = (2, 3))

array([[2, 6, 3],
       [8, 2, 4]])

In [12]:
# 生成[100, 200)之间的随机整数
np.random.randint(100, 200, size = (2, 3))

array([[150, 106, 120],
       [172, 138, 117]])

#### choice

从一个列表或者数组中进行随机采样，或者从某个指定的区间中进行采样生成随机数

In [14]:
# 从数组中随机采样3个数生成一维数组
data = [1, 5, 100, 35, 23, 24, 65, 78, 36]
np.random.choice(data, 4)

array([23,  5, 35, 65])

In [15]:
# 从数组中随机采样生成多维数组
data = [1, 5, 100, 35, 23, 24, 65, 78, 36]
np.random.choice(data, size = (2, 3))

array([[ 78, 100,   1],
       [ 35,   5,  78]])

In [17]:
# 从[0, 5)之间随机采样生成多维数组
np.random.choice(5, size = (2, 3))

array([[4, 1, 1],
       [3, 1, 1]])

#### shuffle

将一个数组中的位置进行混洗打乱

In [25]:
arr = np.arange(10)
print("<arr>\n", arr)
np.random.shuffle(arr)
print("<shuffle arr>\n", arr)

<arr>
 [0 1 2 3 4 5 6 7 8 9]
<shuffle arr>
 [7 0 1 8 3 2 4 5 9 6]
